### ISSUE TITLE
It will not be restored after sliding.

### ISSUE THREAD

**Issue by liuqing520it** [dancormier/react-native-swipeout#268] opened 2018-05-18 14:15 UTC
![image](https://user-images.githubusercontent.com/16216435/40239337-5b2845fa-5ae8-11e8-8bba-58942771dc75.png)
![image](https://user-images.githubusercontent.com/16216435/40239373-6f775d52-5ae8-11e8-9733-afd9ccf6b9dc.png)
![image](https://user-images.githubusercontent.com/16216435/40435542-6f9a9dd6-5ee3-11e8-8697-92fb721fb9be.png)

Swipeout drag will affect the layout of the control on the swipeout, causing the subspaces on the swipeout to shift to the left.

"react": "16.3.1",
"react-native": "0.55.4",
"react-navigation": "^1.1.2",
"react-navigation-redux-helpers": "^1.0.6",
"react-redux": "^5.0.7",
"redux": "^4.0.0"

**Comment by lytieunuong1** [comment] 2018-05-21 09:58
I got the same issue when I tried to use this lib. Here is my code:
`render() {
        const swipeSetting = {
            autoClose: true,
            onClose: (secId, rowId, direction) => {
            },
            onOpen: (secId, rowId, direction) => {
            },
            right: [
                {
                    onPress: () => {
                        
                    },
                    text: 'Delete',type: 'delete'
                }
            ],
            rowId: this.props.item.index,
            sectionId:1
        };
        return (
            <Swipeout {...swipeSetting}>
                <View style={{}}>
                    <View style={{
                        flex: 1, 
                        backgroundColor: 'mediumseagreen',
                        flexDirection: 'row'
                        }}>
                        <Image style={{width:100, height:100, margin: 5}} source={{uri:this.props.item.imageURL}} />
                        <View style={{flex: 1, flexDirection:'column'}}>
                            <Text style={styles.flatListItem}>{this.props.item.name}</Text>
                            <Text style={styles.flatListItem}>{this.props.item.foodDescription}</Text>
                        </View>
                        
                    </View>
                    <View style={{
                        height: 1,
                        backgroundColor: '#dadada'
                    }}
                    ></View>
                </View>
            </Swipeout> 
        );
    }`
And style is:
`const styles = StyleSheet.create({
    flatListItem: {
        color: 'white',
        padding: 10,
        fontSize: 16
    }
});`

Please show me what was wrong... Thanks so much!

**Comment by h5monkey** [comment] 2018-05-23 06:40
I have the same problem, please tell me the answer

**Comment by hamedmam** [comment] 2018-05-25 23:07
same here, cards wont go back to first position (some margin left on right)

**Comment by kunalqss** [comment] 2018-06-13 11:03
Possible duplicate of #267

**Comment by manoj2166** [comment] 2018-06-13 12:54
I have the same issue in iPhone

**Comment by kenanlalic** [comment] 2018-06-14 08:56
try instead of 
```javascript
<Swipeout {...swipeSetting}>
                <View style={{}}>
                   ...
                </View>
</Swipeout> 
```

```javascript
<Swipeout {...swipeSetting}>
                <TouchableWithoutFeedback style={{}}>
                   ...
                </TouchableWithoutFeedback>
</Swipeout> 
```

**Comment by liuqing520it** [comment] 2018-06-22 09:21
update react-native v0.56.0-rc or returning to 0.54.4 fixes the problem.

**Comment by SCJMENGMENG** [comment] 2018-06-25 03:01
npm install --save react-native@0.51

**Comment by markrookie** [comment] 2018-08-20 09:26
Release 2.3.6 fixed this issue

**Comment by amrit-sahoo** [comment] 2018-09-10 12:01
It still appears on 2.3.6

**Closed** 2020-06-10 10:51 UTC
