### ISSUE TITLE
[Build Error] project didn't build

### ISSUE THREAD

**Issue by sqlProvider** [dancormier/react-native-swipeout#230] opened 2017-10-24 11:29 UTC
Please check this error. 

[![image](https://i.hizliresim.com/yz36W7.png)](https://hizliresim.com/yz36W7)

**Comment by kozillla** [comment] 2017-10-24 11:41
have the same issue

**Comment by vysotsky** [comment] 2017-10-24 12:36
@kozillla thanks, it worked pretty cool for me! Can you please explain what's going wrong with it?

**Comment by hushicai** [comment] 2017-10-24 12:58
.babelrc break something...

```
Couldn't find preset \"es2015\" 
```

**Comment by hironarita** [comment] 2017-10-24 15:24
I'm also getting this issue.

**Comment by sytolk** [comment] 2017-10-24 18:37
Remove ^ from version and fixed like that :)
`"react-native-swipeout": "2.2.2"`
the problem is in version 2.3.0 and commit: 
https://github.com/dancormier/react-native-swipeout/commit/f6d0fbce263197b2b3865cf2fc122c694ae07f41

**Comment by almirfilho** [comment] 2017-10-24 22:56
__.babelrc__ file should not be shipped to NPM. I'm going to make a PR to fix this.

**Comment by jasdeepsingh** [comment] 2017-10-25 03:03
have the same issue.

**Comment by silentcloud** [comment] 2017-10-25 03:18
Fixed in 2.3.1

**Closed** 2017-10-25 03:18 UTC
