### ISSUE TITLE
iPhone X view change after a few swipe

### ISSUE THREAD

**Issue by McDreamy** [dancormier/react-native-swipeout#267] opened 2018-05-04 11:02 UTC
At first, it display nicely, but after a few swipes the text is truncated
It only happens in iPhone X.

<img width="935" alt="screen shot 2018-05-04 at 7 03 06 pm" src="https://user-images.githubusercontent.com/9667496/39624941-d93e6be8-4fcd-11e8-8acb-e754b3b6e9c1.png">

**Comment by MaxiBrochon** [comment] 2018-05-20 14:07
Hello, Did anyone find a solution on this issue? 
I have the same problem on iOS

**Comment by dochathuc** [comment] 2018-05-25 14:14
When I go back to "react-native": "^0.49.5", this swipeout lib works fine.
Maybe there are something changed in newest react-native version, so this lib is not compatible with it.

**Comment by McDreamy** [comment] 2018-05-31 03:36
Hi, I solved this issue by wrapping <Text> only with <Swipeout> instead of wrapping the whole <View> with <Swipeout>

<View>
     <Swipeout {...swipeSettings}>
           <Text>Your Text</Text>
      </Swipeout>
</View>

Thank you.

**Comment by mysport12** [comment] 2018-06-05 23:49
Check out this closed issue here: https://github.com/facebook/react-native/issues/19302

**Comment by kunalqss** [comment] 2018-06-13 11:10
Facing the same issue on iPhone (not on Android). Has anybody been able to figure this out ? 
I couldn't understand how to solve this issue from @mysport12's referenced issue[ facebook/react-native#19302](https://github.com/facebook/react-native/issues/19302)

**Comment by mysport12** [comment] 2018-06-13 13:31
PR #274 is addressing the issue @kunalqss

**Comment by kenanlalic** [comment] 2018-06-14 09:03
try instead of

```javascript
<Swipeout {...swipeSetting}>
                <View style={{}}>
                   ...
                </View>
</Swipeout> 
```

```javascript
<Swipeout {...swipeSetting}>
                <TouchableWithoutFeedback style={{}}>
                   ...
                </TouchableWithoutFeedback>
</Swipeout> 
```

**Comment by kunalqss** [comment] 2018-06-19 07:56
@mysport12 So is this issue fixed in the latest release ? Or is it pending ? Because I installed the latest version and the problem still persists in iPhone.

**Comment by kunalqss** [comment] 2018-06-19 07:56
@kenanlalic I was already using <TouchableOpacity> as the child of <SwipeOut>, changing to <TouchableWithoutFeedback> didn't help unfortunately.

**Comment by kunalqss** [comment] 2018-06-19 08:48
Just tried to fix it in my local node module (SwipeOut) using the PR as suggested by @mysport12  and I can confirm that it has fixed this issue. Thank you @mysport12 :)

**Comment by VincentCATILLON** [comment] 2018-07-11 16:17
I got the same issue on iPhone X, and still have it when using the PR #274 from @kunalqss:

![kapture 2018-07-11 at 18 13 56](https://user-images.githubusercontent.com/8419208/42585683-9f75190e-8536-11e8-9f09-ee6660ad6c19.gif)

**Comment by gpaslari** [comment] 2018-07-19 08:38
I'm having the same issue. (Just to emphasise importance of this issue)

**Comment by VincentCATILLON** [comment] 2018-08-07 11:12
@dancormier Can you prioritize this issue please ?

**Comment by markrookie** [comment] 2018-08-20 09:28
You guys should try release 2.3.6 out

**Comment by wangdeng1213** [comment] 2018-09-19 07:55
ok， update 2.3.6 well done！

**Closed** 2019-04-09 11:01 UTC
