### ISSUE TITLE
onClose callback

### ISSUE THREAD

**Issue by yapcheahshen** [dancormier/react-native-swipeout#87] opened 2016-04-12 07:45 UTC
please add

this.props.onClose(this.props.sectionID,this.props.rowID);

after this._tweenContent('contentPos',0);
this.setState({contentPos:0, openedLeft:false,openRight:false});

in _handlePanResponderEnd

so that parent element knows when a swipe is closed.

**Comment by sscaff1** [comment] 2016-04-28 23:13
This would be very helpful.

**Comment by coderdave** [comment] 2016-05-31 13:04
duplicate of https://github.com/dancormier/react-native-swipeout/issues/32 ?

**Comment by silentcloud** [comment] 2017-04-20 04:09
https://github.com/dancormier/react-native-swipeout/commit/76ba2392fac6a0b0905a4309680f2beccf19f79d

**Closed by silentcloud** 2017-04-20 04:09 UTC
